server:
  port: ${BOARD_SERVICE_PORT:8090}

spring:
  application:
    name: board
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${BOARD_DB_URI}
    username: ${BOARD_DB_USERNAME}
    password: ${BOARD_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost }
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka

application:
  config:
    task-url: ${TASK_SERVICE_URL:http://localhost:8080/tasks}