server:
  port: ${TASK_SERVICE_PORT:9090}

spring:
  application:
    name: task
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${TASK_DB_URI}
    username: ${TASK_DB_USERNAME}
    password: ${TASK_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka

application:
  config:
    board-url: ${BOARD_SERVICE_URL:http://localhost:8080/boards}